//
//  ArtBiblePreviewView.swift
//  XRoads
//
//  Created by Nexus on 2026-02-04.
//  US-V4-024: Visual preview for generated art-bible.json tokens
//

import SwiftUI

// MARK: - Art Bible Preview

struct ArtBiblePreviewView: View {
    let artBible: ArtBible

    var body: some View {
        ScrollView {
            VStack(alignment: .leading, spacing: Theme.Spacing.lg) {
                header

                if hasReferences {
                    referencesSection
                }

                if let designTokens = artBible.designTokens {
                    designTokensSection(designTokens)
                }

                if let colorSystem = artBible.colorSystem {
                    colorSystemSection(colorSystem)
                }

                if let typographySystem = artBible.typographySystem {
                    typographySystemSection(typographySystem)
                }

                if !artBible.allComponents.isEmpty {
                    componentsSection(artBible.allComponents)
                }

                if let moodboard = artBible.verbalMoodboard, !moodboard.isEmpty {
                    moodboardSection(moodboard)
                }

                if let photography = artBible.photographyDirection {
                    photographySection(photography)
                }

                if let pages = artBible.pageArchitecture, !pages.isEmpty {
                    pageArchitectureSection(pages)
                }
            }
            .padding(Theme.Spacing.lg)
        }
        .background(Color.bgApp)
    }

    // MARK: - Header

    private var header: some View {
        VStack(alignment: .leading, spacing: Theme.Spacing.xs) {
            Text("Art Bible Preview")
                .font(.system(size: 18, weight: .semibold))
                .foregroundStyle(Color.textPrimary)

            HStack(spacing: Theme.Spacing.sm) {
                Text(artBible.project)
                    .font(.system(size: 13, weight: .medium))
                    .foregroundStyle(Color.textSecondary)

                Text("v\(artBible.version)")
                    .font(.system(size: 12))
                    .foregroundStyle(Color.textTertiary)

                if let generatedAt = artBible.generatedAt {
                    Text(generatedAt.formatted(date: .abbreviated, time: .shortened))
                        .font(.system(size: 11))
                        .foregroundStyle(Color.textTertiary)
                }
            }
        }
        .padding(Theme.Spacing.md)
        .frame(maxWidth: .infinity, alignment: .leading)
        .background(Color.bgSurface)
        .cornerRadius(Theme.Radius.lg)
        .overlay(
            RoundedRectangle(cornerRadius: Theme.Radius.lg)
                .stroke(Color.borderDefault, lineWidth: 1)
        )
    }

    // MARK: - Sections

    private var hasReferences: Bool {
        !(artBible.referenceURLs ?? []).isEmpty || !(artBible.imageReferences ?? []).isEmpty
    }

    private var referencesSection: some View {
        VStack(alignment: .leading, spacing: Theme.Spacing.sm) {
            sectionHeader(title: "References", subtitle: "Input images and links used for generation")

            if let urls = artBible.referenceURLs, !urls.isEmpty {
                referenceList(title: "Reference URLs", items: urls)
            }

            if let images = artBible.imageReferences, !images.isEmpty {
                referenceList(title: "Image References", items: images)
            }
        }
        .cardStyle()
        .padding(.bottom, Theme.Spacing.sm)
    }

    private func designTokensSection(_ tokens: ArtBibleDesignTokens) -> some View {
        VStack(alignment: .leading, spacing: Theme.Spacing.md) {
            sectionHeader(title: "Design Tokens", subtitle: "Core colors, typography, spacing, radius")

            if let colors = tokens.colors {
                ForEach(colors.keys.sorted(), id: \.self) { category in
                    if let values = colors[category] {
                        tokenColorGrid(title: category.capitalized, colors: values)
                    }
                }
            }

            if let typography = tokens.typography {
                typographyTokensSection(typography)
            }

            if let spacing = tokens.spacing {
                tokenChipSection(title: "Spacing", values: spacing)
            }

            if let radius = tokens.radius {
                tokenChipSection(title: "Radius", values: radius)
            }
        }
        .cardStyle()
    }

    private func colorSystemSection(_ colors: [String: ArtBibleColorSwatch]) -> some View {
        VStack(alignment: .leading, spacing: Theme.Spacing.md) {
            sectionHeader(title: "Color System", subtitle: "Semantic palette generated by the art director")

            LazyVGrid(columns: [GridItem(.adaptive(minimum: 140), spacing: Theme.Spacing.sm)], spacing: Theme.Spacing.sm) {
                ForEach(colors.keys.sorted(), id: \.self) { key in
                    if let swatch = colors[key] {
                        ColorSwatchView(
                            title: key.replacingOccurrences(of: "_", with: " ").capitalized,
                            hex: swatch.hex,
                            usage: swatch.usage ?? swatch.name
                        )
                    }
                }
            }
        }
        .cardStyle()
    }

    private func typographySystemSection(_ typography: [String: ArtBibleTypographySpec]) -> some View {
        VStack(alignment: .leading, spacing: Theme.Spacing.sm) {
            sectionHeader(title: "Typography System", subtitle: "Type scales and styles")

            ForEach(typography.keys.sorted(), id: \.self) { key in
                if let spec = typography[key] {
                    TypographyRow(title: key.capitalized, spec: spec)
                }
            }
        }
        .cardStyle()
    }

    private func componentsSection(_ components: [ArtBibleComponent]) -> some View {
        VStack(alignment: .leading, spacing: Theme.Spacing.sm) {
            sectionHeader(title: "UI Components", subtitle: "Generated component specifications")

            ForEach(components, id: \.name) { component in
                VStack(alignment: .leading, spacing: 6) {
                    Text(component.name)
                        .font(.system(size: 13, weight: .semibold))
                        .foregroundStyle(Color.textPrimary)

                    if let description = component.description {
                        Text(description)
                            .font(.system(size: 12))
                            .foregroundStyle(Color.textSecondary)
                    }

                    if let tokens = component.tokens, !tokens.isEmpty {
                        Text("Tokens: \(tokens.joined(separator: ", "))")
                            .font(.system(size: 11))
                            .foregroundStyle(Color.textTertiary)
                    }

                    if let style = component.styleSpecs, !style.isEmpty {
                        let summary = style.map { "\($0.key): \($0.value.displayValue)" }.sorted().joined(separator: " • ")
                        Text(summary)
                            .font(.system(size: 11))
                            .foregroundStyle(Color.textTertiary)
                    }
                }
                .padding(Theme.Spacing.sm)
                .background(Color.bgElevated)
                .cornerRadius(Theme.Radius.sm)
            }
        }
        .cardStyle()
    }

    private func moodboardSection(_ moodboard: [ArtBibleMoodboard]) -> some View {
        VStack(alignment: .leading, spacing: Theme.Spacing.sm) {
            sectionHeader(title: "Verbal Moodboard", subtitle: "Visual DNA summaries")

            ForEach(Array(moodboard.enumerated()), id: \.offset) { _, entry in
                VStack(alignment: .leading, spacing: 4) {
                    Text(entry.description)
                        .font(.system(size: 12))
                        .foregroundStyle(Color.textPrimary)

                    if let keywords = entry.keywords, !keywords.isEmpty {
                        Text(keywords.joined(separator: " • "))
                            .font(.system(size: 11))
                            .foregroundStyle(Color.textTertiary)
                    }
                }
                .padding(Theme.Spacing.sm)
                .background(Color.bgElevated)
                .cornerRadius(Theme.Radius.sm)
            }
        }
        .cardStyle()
    }

    private func photographySection(_ photography: ArtBiblePhotographyDirection) -> some View {
        VStack(alignment: .leading, spacing: Theme.Spacing.sm) {
            sectionHeader(title: "Photography Direction", subtitle: "Lighting, style, and AI prompts")

            if let style = photography.style {
                infoRow(label: "Style", value: style)
            }
            if let lighting = photography.lighting {
                infoRow(label: "Lighting", value: lighting)
            }
            if let composition = photography.composition {
                infoRow(label: "Composition", value: composition)
            }

            if let prompts = photography.aiPrompts, !prompts.isEmpty {
                Text("AI Prompts")
                    .font(.system(size: 11, weight: .semibold))
                    .foregroundStyle(Color.textSecondary)

                ForEach(prompts, id: \.self) { prompt in
                    Text(prompt)
                        .font(.system(size: 11))
                        .foregroundStyle(Color.textTertiary)
                        .padding(.vertical, 2)
                }
            }
        }
        .cardStyle()
    }

    private func pageArchitectureSection(_ pages: [ArtBiblePage]) -> some View {
        VStack(alignment: .leading, spacing: Theme.Spacing.sm) {
            sectionHeader(title: "Page Architecture", subtitle: "Layouts and sections")

            ForEach(pages, id: \.page) { page in
                VStack(alignment: .leading, spacing: 6) {
                    Text(page.page)
                        .font(.system(size: 13, weight: .semibold))
                        .foregroundStyle(Color.textPrimary)

                    if let sections = page.sections {
                        ForEach(sections, id: \.name) { section in
                            VStack(alignment: .leading, spacing: 2) {
                                Text(section.name)
                                    .font(.system(size: 12, weight: .semibold))
                                    .foregroundStyle(Color.textSecondary)

                                if let purpose = section.purpose {
                                    Text(purpose)
                                        .font(.system(size: 11))
                                        .foregroundStyle(Color.textTertiary)
                                }
                            }
                            .padding(.vertical, 2)
                        }
                    }
                }
                .padding(Theme.Spacing.sm)
                .background(Color.bgElevated)
                .cornerRadius(Theme.Radius.sm)
            }
        }
        .cardStyle()
    }

    // MARK: - Helpers

    private func sectionHeader(title: String, subtitle: String? = nil) -> some View {
        VStack(alignment: .leading, spacing: 2) {
            Text(title)
                .font(.system(size: 13, weight: .semibold))
                .foregroundStyle(Color.textPrimary)

            if let subtitle {
                Text(subtitle)
                    .font(.system(size: 11))
                    .foregroundStyle(Color.textTertiary)
            }
        }
    }

    private func referenceList(title: String, items: [String]) -> some View {
        VStack(alignment: .leading, spacing: 4) {
            Text(title)
                .font(.system(size: 11, weight: .semibold))
                .foregroundStyle(Color.textSecondary)

            ForEach(items, id: \.self) { item in
                Text(item)
                    .font(.system(size: 11))
                    .foregroundStyle(Color.textTertiary)
                    .lineLimit(2)
                    .truncationMode(.middle)
            }
        }
        .padding(.vertical, 4)
    }

    private func tokenColorGrid(title: String, colors: [String: String]) -> some View {
        VStack(alignment: .leading, spacing: Theme.Spacing.xs) {
            Text(title)
                .font(.system(size: 12, weight: .semibold))
                .foregroundStyle(Color.textSecondary)

            LazyVGrid(columns: [GridItem(.adaptive(minimum: 120), spacing: Theme.Spacing.sm)], spacing: Theme.Spacing.sm) {
                ForEach(colors.keys.sorted(), id: \.self) { key in
                    if let hex = colors[key] {
                        ColorSwatchView(title: key.capitalized, hex: hex, usage: nil)
                    }
                }
            }
        }
    }

    private func typographyTokensSection(_ typography: ArtBibleTypographyTokens) -> some View {
        VStack(alignment: .leading, spacing: 6) {
            if let families = typography.fontFamily, !families.isEmpty {
                Text("Fonts")
                    .font(.system(size: 11, weight: .semibold))
                    .foregroundStyle(Color.textSecondary)

                ForEach(families.keys.sorted(), id: \.self) { key in
                    if let font = families[key] {
                        infoRow(label: key.capitalized, value: font)
                    }
                }
            }

            if let sizes = typography.sizes, !sizes.isEmpty {
                tokenChipSection(title: "Type Sizes", values: sizes)
            }
        }
    }

    private func tokenChipSection(title: String, values: [String: Double]) -> some View {
        VStack(alignment: .leading, spacing: Theme.Spacing.xs) {
            Text(title)
                .font(.system(size: 11, weight: .semibold))
                .foregroundStyle(Color.textSecondary)

            PRDFlowLayout(spacing: 6) {
                ForEach(values.keys.sorted(), id: \.self) { key in
                    if let value = values[key] {
                        TokenChip(label: key.uppercased(), value: value)
                    }
                }
            }
        }
    }

    private func infoRow(label: String, value: String) -> some View {
        HStack(alignment: .top, spacing: Theme.Spacing.sm) {
            Text(label)
                .font(.system(size: 11, weight: .semibold))
                .foregroundStyle(Color.textSecondary)
                .frame(width: 90, alignment: .leading)

            Text(value)
                .font(.system(size: 11))
                .foregroundStyle(Color.textTertiary)
        }
    }
}

// MARK: - Supporting Views

private struct ColorSwatchView: View {
    let title: String
    let hex: String
    let usage: String?

    var body: some View {
        VStack(alignment: .leading, spacing: 6) {
            RoundedRectangle(cornerRadius: Theme.Radius.xs)
                .fill(Color(hex: hex))
                .frame(height: 24)
                .overlay(
                    RoundedRectangle(cornerRadius: Theme.Radius.xs)
                        .stroke(Color.borderDefault, lineWidth: 1)
                )

            Text(title)
                .font(.system(size: 11, weight: .semibold))
                .foregroundStyle(Color.textPrimary)

            Text(hex.uppercased())
                .font(.system(size: 10))
                .foregroundStyle(Color.textTertiary)

            if let usage {
                Text(usage)
                    .font(.system(size: 10))
                    .foregroundStyle(Color.textSecondary)
                    .lineLimit(2)
            }
        }
        .padding(Theme.Spacing.sm)
        .background(Color.bgElevated)
        .cornerRadius(Theme.Radius.sm)
    }
}

private struct TypographyRow: View {
    let title: String
    let spec: ArtBibleTypographySpec

    var body: some View {
        VStack(alignment: .leading, spacing: 2) {
            Text(title)
                .font(.system(size: 12, weight: .semibold))
                .foregroundStyle(Color.textPrimary)

            let details = [
                spec.font.map { "Font: \($0)" },
                spec.weight.map { "Weight: \(Int($0))" },
                spec.size.map { "Size: \(Int($0))" },
                spec.sizeDesktop.map { "Desktop: \(Int($0))" },
                spec.sizeMobile.map { "Mobile: \(Int($0))" },
                spec.letterSpacing.map { "Tracking: \($0)" },
                spec.lineHeight.map { "Line Height: \($0)" },
                spec.caseStyle.map { "Case: \($0)" }
            ].compactMap { $0 }

            if !details.isEmpty {
                Text(details.joined(separator: " • "))
                    .font(.system(size: 11))
                    .foregroundStyle(Color.textSecondary)
            }
        }
        .padding(Theme.Spacing.sm)
        .background(Color.bgElevated)
        .cornerRadius(Theme.Radius.sm)
    }
}

private struct TokenChip: View {
    let label: String
    let value: Double

    var body: some View {
        HStack(spacing: 4) {
            Text(label)
                .font(.system(size: 10, weight: .semibold))
                .foregroundStyle(Color.textSecondary)

            Text(String(format: "%.0f", value))
                .font(.system(size: 10))
                .foregroundStyle(Color.textPrimary)
        }
        .padding(.horizontal, 8)
        .padding(.vertical, 4)
        .background(Color.accentPrimary.opacity(0.12))
        .cornerRadius(12)
    }
}

// MARK: - Preview

#if DEBUG
struct ArtBiblePreviewView_Previews: PreviewProvider {
    static var previews: some View {
        ArtBiblePreviewView(artBible: .previewSample)
            .frame(width: 900, height: 700)
            .background(Color.bgApp)
    }
}

private extension ArtBible {
    static var previewSample: ArtBible {
        ArtBible(
            project: "XRoads",
            version: "1.0.0",
            generatedAt: Date(),
            verbalMoodboard: [
                ArtBibleMoodboard(
                    description: "A precision-engineered command center with neon accents.",
                    keywords: ["dark", "professional", "futuristic"],
                    aiPrompt: ""
                )
            ],
            designTokens: ArtBibleDesignTokens(
                colors: [
                    "background": ["primary": "#0d1117", "secondary": "#161b22"],
                    "accent": ["primary": "#388bfd", "secondary": "#3fb950"],
                    "text": ["primary": "#e6edf3", "secondary": "#7d8590"]
                ],
                typography: ArtBibleTypographyTokens(
                    fontFamily: ["ui": "SF Pro", "mono": "SF Mono"],
                    sizes: ["xs": 10, "sm": 12, "md": 14, "lg": 16, "xl": 20]
                ),
                spacing: ["xs": 4, "sm": 8, "md": 16, "lg": 24, "xl": 32],
                radius: ["sm": 4, "md": 8, "lg": 12]
            ),
            components: [
                ArtBibleComponent(
                    name: "PrimaryButton",
                    description: "Primary CTA button",
                    tokens: ["accent.primary", "radius.md"],
                    styleSpecs: ["radius": .number(8), "padding": .number(16)],
                    visualPrompt: nil,
                    interaction: nil
                )
            ],
            referenceURLs: ["https://example.com/reference"],
            imageReferences: ["/path/to/reference.png"]
        )
    }
}
#endif
